Models/Campuses/Export.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace SP23_G21_SHSMS.Models.Campuses;

public partial class Export
{
    public int ExportId { get; set; }

    public int? UserId { get; set; }

    public int? MedicalRecordsId { get; set; }

    public float? Amount { get; set; }

    public DateTime? ExportDate { get; set; }

    public int? ExportTypeId { get; set; }

    public string? Note { get; set; }

    public bool? Status { get; set; }

    [JsonIgnore]
    public virtual ICollection<ExportDetail> ExportDetails { get; } = new List<ExportDetail>();

    public virtual ExportType? ExportType { get; set; }

    public virtual MedicalRecord? MedicalRecords { get; set; }
}

Models/Campuses/ExportType.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace SP23_G21_SHSMS.Models.Campuses;

public partial class ExportType
{
    public int ExportTypeId { get; set; }

    public string? ExportTypeName { get; set; }

    [JsonIgnore]
    public virtual ICollection<Export> Exports { get; } = new List<Export>();
}

Controllers/Commons/ExportsController.cs
using System.Dynamic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using SP23_G21_SHSMS.Models.Campuses;
using SP23_G21_SHSMS.Models.SHSMS;
using SP23_G21_SHSMS.Services.Campus_Services.ExportServices;
using SP23_G21_SHSMS.Services.Campus_Services.MedicalRecordServices;
using SP23_G21_SHSMS.Services.Campus_Services.StudentServices;
using SP23_G21_SHSMS.Services.Campus_Services.SymptomServices;
using SP23_G21_SHSMS.Services.Campus_Services.TreatmentServices;
using SP23_G21_SHSMS.Services.SHSMS_Services.CategoryServices;
using SP23_G21_SHSMS.Services.SHSMS_Services.DiseaseServices;
using SP23_G21_SHSMS.Services.SHSMS_Services.MedicineServices;
using SP23_G21_SHSMS.Services.SHSMS_Services.UserServices;

namespace SP23_G21_SHSMS.Controllers.Commons
{
    public class ExportsController : Controller
    {
        private DbCampusContext _campusContext;
        private DbShsmsContext _shsmsContext;
        private IExportSv _exportSv;
        private IMedicalRecordSv _medicalRecordSv;
        private IMedicineSv _medicineSv;
        private ISymptomSv _symptomSv;
        private IStudentSv _studentSv;
        private IDiseaseSv _diseaseSv;
        private IUserSv _userSv;
        private ITreatmentSv _treatmentSv;
        private ICategorySv _categorySv;
        private dynamic models;
        public ExportsController(DbCampusContext campusContext, DbShsmsContext shsmsContext)
        {
            _campusContext = campusContext;
            _shsmsContext = shsmsContext;
            _exportSv = new ExportSvImpl(_campusContext);
            _medicalRecordSv = new MedicalRecordSvImpl(_campusContext);
            _symptomSv = new SymptomSvImpl(_campusContext);
            _medicineSv = new MedicineSvImpl(_shsmsContext);
            _studentSv = new StudentSvImpl(_campusContext);
            _diseaseSv = new DiseaseSvImpl(_shsmsContext);
            _userSv = new UserSvImpl(_shsmsContext);
            _treatmentSv = new TreatmentSvImpl(_campusContext);
            _categorySv = new CategorySvImpl(_shsmsContext);
            models = new ExpandoObject();
        }

        // GET: Exports
        public async Task<IActionResult> Index()
        {
            var dbCampusContext = _campusContext.Exports.Include(e => e.MedicalRecords);
            return View(await dbCampusContext.ToListAsync());
        }

        // GET: Exports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _campusContext.Exports == null)
            {
                return RedirectToAction(nameof(Index));
            }

            //TODO: Gọi đến exports services
            var export = await _campusContext.Exports
                .Include(e => e.MedicalRecords)
                .Include(e => e.ExportType)
                .FirstOrDefaultAsync(m => m.ExportId == id);

            if (export == null)
            {
                return NotFound();
            }

            MedicalRecord medicalRecord = _medicalRecordSv.GetMedicalRecordById(export.MedicalRecordsId.Value);
            Student student = _studentSv.FindStudentByRollNumber(medicalRecord.RollNumber);
            //TODO: Gọi đến exportDetails services (chưa sửa đc services và repo vì có commits on change file này)
            IEnumerable<ExportDetail> exportDetails = _campusContext.ExportDetails
                .Include(e => e.Export)
                .Include(e => e.Storage)
                .Where(e => e.ExportId == export.ExportId)
                .ToList();
            IEnumerable<Medicine> medicines = _medicineSv.GetMedicines();
            IEnumerable<User> users = _userSv.GetUsers();

            models.MedicalRecord = medicalRecord;
            models.Users = users;
            models.Student = student;
            models.Export = export;
            models.ExportDetails = exportDetails;
            models.Medicines = medicines;
            return View(models);
        }

        // GET: Exports/Create
        public IActionResult Create(int? id)
        {
            //id này là của medicalRecord
            if (id != null)
            {
                var record = _medicalRecordSv.GetMedicalRecordById(id.Value);
                models.Medicines = _medicineSv.GetMedicines();
                models.Students = _studentSv.GetStudents();
                models.Users = _userSv.GetUsers();
                models.Symptoms = record.Symptoms;
                models.Diseases = _diseaseSv.GetDiseases();
                models.MedicalRecord = record;
                models.Treatments = _treatmentSv.GetTreatments();
                models.Export = new Export();
                models.ExportDetail = new ExportDetail();
                List<Category> categories = new List<Category>(_categorySv.GetCategories());
                models.ListOfCategory = categories;
                var export = new Export();
                export.MedicalRecordsId = id.Value;
                ViewData["MedicalRecordsId"] = new SelectList(_medicalRecordSv.GetMedicalRecords(), "MedicalRecordsId", "MedicalRecordsId", export.MedicalRecordsId);
            }
            else
            {
                ViewData["MedicalRecordsId"] = new SelectList(_campusContext.MedicalRecords, "MedicalRecordsId", "MedicalRecordsId");
            }
            return View(models);
        }

        // POST: Exports/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string txtRecordId, string txtAmount, string txtNote)
        {
            var userTmp = HttpContext.Session.GetString("User");
            User user = JsonConvert.DeserializeObject<User>(userTmp);
            Export export = new Export();
            var selectedMedicines = Request.Form["slMedicine"];
            var selectedQuantity = Request.Form["txtQuantity"];
            var selectedDirection = Request.Form["txtDirection"];
            int checkQuantity;
            for (int i = 0; i < selectedQuantity.Count; i++)
            {
                if (int.TryParse(selectedQuantity[i], out checkQuantity))
                    continue;
                else
                {
                    //TODO: Message Error
                    break;
                }
            }

            IDictionary<string, int> dictMedicinesQuantity = new Dictionary<string, int>();
            for (int i = 0; i < selectedMedicines.Count; i++)
            {
                int quantity;
                if (!dictMedicinesQuantity.ContainsKey(selectedMedicines[i]))
                {
                    dictMedicinesQuantity.Add(selectedMedicines[i], int.Parse(selectedQuantity[i]));
                }
                else
                {
                    dictMedicinesQuantity[selectedMedicines[i]] += int.Parse(selectedQuantity[i]);
                }
            }

            IDictionary<string, string> dictMedicinesDirection = new Dictionary<string, string>();
            for (int i = 0; i < selectedMedicines.Count; i++)
            {
                if (!dictMedicinesDirection.ContainsKey(selectedMedicines[i]))
                {
                    dictMedicinesDirection.Add(selectedMedicines[i], selectedDirection[i]);
                }
            }

            float total = 0;
            foreach (var item in dictMedicinesQuantity)
            {
                int quantity = item.Value;
                var medicine = _medicineSv.GetMedicineById(item.Key);

                //TODO: Lấy danh sách kho có thuốc có thuốc cần lấy
                var storages = GetStoragesByMedicineId(item.Key);
                int quantityTmp = quantity;

                List<Storage> listStorage = new List<Storage>();

                //TODO: kiểm tra xem tổng số lượng có sản phẩm cần tìm trong kho có >= quantity ko; nếu có thì thực hiện, ko thì phải báo lỗi
                //if(service storage get quantity of all storage have medicineId >= quantity)
                foreach (Storage storage in storages)
                {
                    if (storage.Quantity - quantity >= 0)
                    {
                        listStorage.Add(storage);
                        quantity = 0;
                        break;
                    }
                    else
                    {
                        listStorage.Add(storage);
                        quantity -= storage.Quantity is null ? 0 : storage.Quantity.Value;
                    }
                }

                foreach (Storage storage in listStorage)
                {
                    ExportDetail exportDetail = new ExportDetail();
                    if (quantityTmp - storage.Quantity > 0)
                    {
                        exportDetail.Quantity = storage.Quantity;
                        quantityTmp -= storage.Quantity is null ? 0 : (int)storage.Quantity.Value;
                        //TODO:update quantity trong storage
                        storage.Quantity = 0;
                    }
                    else
                    {
                        exportDetail.Quantity = quantityTmp;
                        //TODO:update quantity trong storage
                        storage.Quantity -= quantityTmp;
                        quantityTmp = 0;
                    }

                    exportDetail.StorageId = storage.StorageId;

                    //TODO: Lấy giá tiền của thuốc khi nhập
                    //TODO: Lấy giá từng loại thuốc khi nhập!
                    if (medicine.IsFree == true)
                    {
                        exportDetail.Price = 0;
                    }
                    else
                    {
                        exportDetail.Price = 1300;
                    }

Views/Exports/Delete.cshtml
@model SP23_G21_SHSMS.Models.Campuses.Export

@{
    ViewData["Title"] = "Export Delete";
}

<h1>Export Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Export</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExportDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExportDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MedicalRecords)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MedicalRecords.MedicalRecordsId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ExportId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Exports/Details.cshtml
@using SP23_G21_SHSMS.Models.Campuses;
@using SP23_G21_SHSMS.Models.SHSMS;
@model dynamic

@{
    ViewData["Title"] = "Chi tiết đơn thuốc";
    Student student = Model.Student;
    Export export = Model.Export;
    MedicalRecord record = Model.MedicalRecord;
    IEnumerable<ExportDetail> exportDetails = Model.ExportDetails;
    IEnumerable<Medicine> medicines = Model.Medicines;
    IEnumerable<User> users = Model.Users;
}

<div class="container px-4 py-5">
    <div class="card card-cover rounded-4 shadow-lg">
        <p class="pb-2 border-bottom mx-4 my-3 text-secondary text-center h3">Thông tin hồ sơ</p>
        <div class="container">
            <div class="table-responsive mx-3">
                <table class="table table-bordered">
                    <tr>
                        <td style="width: 15%;" class="table-light">@Html.DisplayNameFor(modelItem => student.StudentName)</td>
                        <td style="width: 35%;" class="fw-bold">
                            @{
                                if (!student.RollNumber.ToLower().Equals("Temp".ToLower()))
                                {
                                    @Html.DisplayFor(modelItem => student.StudentName)
                                    @Html.Raw(" - ")
                                    @Html.DisplayFor(model => student.RollNumber)
                                }
                                if (student.RollNumber.ToLower().Equals("Temp".ToLower()))
                                {
                                    <a asp-controller="MedicalRecords" asp-action="Edit" asp-route-id="@export.MedicalRecordsId" class="text-decoration-none text-danger">Cập nhật thông tin</a>
                                }
                            }
                        </td>
                        <td style="width: 15%;" class="table-light">Người khám</td>
                        <td style="width: 35%;" class="fw-bold">
                            @foreach (var u in users)
                            {
                                if (u.UserId == record.UserId)
                                {
                                    @Html.DisplayFor(modelItem => u.UserName)
                                    break;
                                }
                            }
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 15%;" class="table-light">Ngày tạo đơn thuốc</td>
                        <td style="width: 35%;" class="fw-bold">
                            
                            @{
                                var time = export.ExportDate?.ToString("dd/MM/yyyy hh:mm:ss");
                            }
                            @time
                        </td>
                        <td style="width: 15%;" class="table-light">Tổng tiền</td>
                        <td style="width: 35%;" class="fw-bold">@Html.DisplayFor(modelItem => export.Amount)</td>
                    </tr>
                    <tr>
                        <td style="width: 15%;" class="table-light">Ghi chú</td>
                        <td style="width: 35%;" class="fw-bold">@Html.DisplayFor(modelItem => export.Note)</td>
                        <td style="width: 15%;" class="table-light">Loại đơn xuất</td>
                        <td style="width: 35%;" class="fw-bold">@Html.DisplayFor(modelItem => export.ExportType.ExportTypeName)</td>
                    </tr>
                </table>
            </div>
        </div>
        @*Start*@
        <p class="pb-2 border-bottom mx-4 my-3 text-secondary text-center h3">
            Chi tiết đơn thuốc
        </p>
        <div class="container">
            <div class="table-responsive mx-3">
                <table class="table table-bordered table-hover">
                    <thead class="table-light">
                        <tr>
                            <th class="text-center">
                                #
                            </th>
                            <th>
                                Lô thuốc
                            </th>
                            <th>
                                Tên thuốc
                            </th>
                            <th>
                                Số lượng
                            </th>
                            <th>
                                Giá tiền
                            </th>
                            <th>
                                Tổng tiền
                            </th>
                            <th>
                                HDSD
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int count2 = 0;
                        }
                        @foreach (var exportDetail in exportDetails)
                        {
                            <tr>
                                <td class="text-center">
                                    @(++count2)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => exportDetail.StorageId)
                                </td>
                                <td>
                                    @foreach (var medicine in medicines)
                                    {
                                        if (medicine.MedicineId.ToLower().Equals(exportDetail.Storage.MedicineId.ToLower()))
                                        {
                                            @Html.DisplayFor(modelItem => medicine.MedicineName)
                                            break;
                                        }
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => exportDetail.Quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => exportDetail.Price)
                                </td>
                                <td>
                                    @(exportDetail.Price * exportDetail.Quantity)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => exportDetail.Direction)
                                </td>
                                @*<td>
                            <a asp-action="Edit" asp-route-id="@item.ExportId">Edit</a> |
                            <a asp-controller="Exports" asp-action="Details" asp-route-id="@item.ExportId">Details</a>
                            | <a asp-action="Delete" asp-route-id="@item.ExportId">Delete</a>
                            </td>*@
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        @*End*@
    </div>
</div>

<div class="container">
    @*<a asp-action="Edit" asp-route-id="">Sửa</a> |*@
    <a asp-controller="MedicalRecords" asp-action="Details" asp-route-id="@record.MedicalRecordsId" class="btn btn-secondary  float-end">Quay lại</a>
</div>

Views/Exports/Edit.cshtml
@model SP23_G21_SHSMS.Models.Campuses.Export

@{
    ViewData["Title"] = "Export Edit";
}

<h1>Export Edit</h1>

<h4>Export</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ExportId" />
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <input asp-for="UserId" class="form-control" />
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicalRecordsId" class="control-label"></label>
                <select asp-for="MedicalRecordsId" class="form-control" asp-items="ViewBag.MedicalRecordsId"></select>
                <span asp-validation-for="MedicalRecordsId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExportDate" class="control-label"></label>
                <input asp-for="ExportDate" class="form-control" />
                <span asp-validation-for="ExportDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Exports/Index.cshtml
@model IEnumerable<SP23_G21_SHSMS.Models.Campuses.Export>

@{
    ViewData["Title"] = "Exports";
}

<h1>Export</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExportDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MedicalRecords)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExportDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MedicalRecords.MedicalRecordsId)
                </td>
                <td>
                    @*<a asp-action="Edit" asp-route-id="@item.ExportId">Edit</a> |*@
                    <a asp-action="Details" asp-route-id="@item.ExportId">Details</a>
                    @*| <a asp-action="Delete" asp-route-id="@item.ExportId">Delete</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Exports/Test.cshtml
@model SP23_G21_SHSMS.Models.SHSMS.Category
@{
    <form asp-controller="Exports" asp-action="TestPost" method="post">
        <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
        <label asp-for="CategoryName" class="control-label"></label>
        <select asp-for="CategoryId" class="form-select" asp-items="@(new SelectList(ViewBag.ListOfCategory,"CategoryId","CategoryName"))"></select>
        <hr />
        <label class="control-label">Medicine Name</label>
        <select class="form-select" id="slMedicine" asp-items="@(new SelectList(string.Empty,"MedicineId","MedicineName"))"></select>
        <hr />
    </form>
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            var items = "<option value='0'>Select</option>";
            $('#slMedicine').html(items);
            $('#CategoryId').change(function () {
                var url = "/Exports/GetMedicines";
                var ddlsource = '#CategoryId';
                console.log('Url: ' + url);
                console.log('ddlsource: ' + ddlsource);

                $.ajax({
                    type: "GET",
                    url: "/Exports/GetMedicines",
                    data: { categoryId: $("#CategoryId").val() },
                    success: function (response, status, xhr) {
                        console.log("Response: " + response);
                        console.log("#CategoryId: " + $("#CategoryId").val());
                        if (response == null) {
                            console.log("Bi null roiiiii!!!");
                        } else {
                            $("#slMedicine").empty();
                            $.each(response, function (index, value) {
                                console.log("MedicineId:" + value.MedicineId + ", MedicineName:" + value.MedicineName);
                                $("#slMedicine").append("<option value='" + value.MedicineId + "'>" + value.MedicineName + "</option>")
                            });
                        }
                    },
                    error: function (response) {
                        console.log("ERROR");
                    }
                });
            });
        });
    </script>
}